name: flutter_avif_windows
description: Windows implementation for flutter_avif.
version: 2.4.1
repository: https://github.com/yekeskin/flutter_avif/tree/main/flutter_avif_windows

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface:
      git:
        url: https://github.com/Kevin301099/flutter_avif
        path: flutter_avif_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
flutter:
  plugin:
    implements: flutter_avif
    platforms:
      windows:
        pluginClass: FlutterAvifWindowsPlugin
        dartPluginClass: FlutterAvifWindows
