name: flutter_avif
description: A flutter plugin to view and encode avif images using libavif.
version: 2.4.1
repository: https://github.com/yekeskin/flutter_avif

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_avif_platform_interface:
      git:
        url: https://github.com/Kevin301099/flutter_avif
        path: flutter_avif_platform_interface
  flutter_avif_android:
      git:
        url: https://github.com/Kevin301099/flutter_avif
        path: flutter_avif_android
  flutter_avif_ios:
      git:
        url: https://github.com/Kevin301099/flutter_avif
        path: flutter_avif_ios
  flutter_avif_macos:
      git:
        url: https://github.com/Kevin301099/flutter_avif
        path: flutter_avif_macos
  flutter_avif_linux:
      git:
        url: https://github.com/Kevin301099/flutter_avif
        path: flutter_avif_linux
  flutter_avif_windows:
      git:
        url: https://github.com/Kevin301099/flutter_avif
        path: flutter_avif_windows
  flutter_avif_web:
      git:
        url: https://github.com/Kevin301099/flutter_avif
        path: flutter_avif_web
  http: ^1.2.0
  exif: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3
  
flutter:
  plugin:
    platforms:
      android:
        default_package: flutter_avif_android
      ios:
        default_package: flutter_avif_ios
      macos:
        default_package: flutter_avif_macos
      linux:
        default_package: flutter_avif_linux
      windows:
        default_package: flutter_avif_windows
      web:
        default_package: flutter_avif_web
